import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import {ThemeProvider} from '@/components/ThemeProvider';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
    weight: ['400', '700'], // Optional: add other weights as needed
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${roboto.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system"
                       enableSystem
                       disableTransitionOnChange>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
